### ISSUE TITLE
Feature Request -- Ability to pull reminders from the 'Today' tab

### ISSUE THREAD

**Issue by tallguyjenks** [urishiraval/obsidian-apple-reminders-plugin#1]
Being able to pull reminders only due today and potentially showing the date/time they are due would drastically increase the usability of this plugin (which i love adding to my daily template) :)

**Comment by urishiraval** [comment]
@tallguyjenks This is definitely in the pipeline...I'm going to implement some basic filters (for now at least) and that should greatly improve usability

**Comment by tallguyjenks** [comment]
woot!

**Comment by urishiraval** [comment]
Hey @tallguyjenks
I've created some basic filters....let me know if that solves the problem. If it does I can close this issue 😄
