### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DesignDan42** [urishiraval/obsidian-apple-reminders-plugin#11]
Such an useful plugin, but ut doesn't work. The tasks from reminders are not being pulled.

What does "Enable Apple Reminders in Third-Party Plugins" mean? In Obsidian, or in "security & privacy" Settings on the mac?

Cheers

**Comment by jscottee** [comment]
I know, this would be groundbreaking for me if it worked! 

To your question—I think the author meant enabling "Apple Reminders" in Obsidian's "Community Plugins" tab. Still didn't work for me, though.

Side note: in the Mac Preferences "Security & Privacy" section, I did not find any options to enable Obsidian for elevated privileges. I tried granting Obsidian full disk access just in case, but it still wouldn't pull data from the Reminders app.

(Using macOS 12.5.1, and Reminders v7.0.)

**Comment by urishiraval** [comment]
@DesignDan42  and @jscottee Please update the plugin and try again.

Do let me know if there are still issues

**Comment by jscottee** [comment]
Just updated and followed the example code as given in the README:

`
```reminders
list: Reminders
```
`
I have a few uncompleted reminders in this list, but the Obsidian note stays empty.

**Comment by happytk** [comment]
Context name should be "apple-reminders"  not "reminders".

https://github.com/urishiraval/obsidian-apple-reminders-plugin/blob/3bbdea125afe29e9623165503390dd55158d69e1/src/main.ts#L48

**Comment by urishiraval** [comment]
@happytk you are a lifesaver!

If that was indeed the issue can I close this bug out?

I will update the documentation now and close this with the PR.

**Comment by DesignDan42** [comment]
It works which is amazing!!! But it looks awful, and I cannot change the CSS to look properly…



Does it look like this for you guys as well?

Cheers!
Dan

**Comment by urishiraval** [comment]
Could you attach a screenshot?

**Comment by DesignDan42** [comment]
Sure! Here you go:


Cheers
Dan

**Comment by Calorion** [comment]
```
```reminders
list: List Name
```
```

**Comment by Calorion** [comment]
````
```apple-reminders
list: List Name
````

**Comment by urishiraval** [comment]
Will continue this in the other issue you created
