### ISSUE TITLE
Not compatible with iPad?

### ISSUE THREAD

**Issue by Calorion** [urishiraval/obsidian-apple-reminders-plugin#12]
The docs say it supports Apple devices, but when I try to install on iPad it says, "this plugin does not support your device."

**Comment by nonissue** [comment]
The plugin relies on AppleScript, which isn't available on iOS/iPadOS. I suggest this be closed.

**Comment by Calorion** [comment]
Then perhaps change the documentation to avoid confusion.

Better yet, find a way to support iOS!

**Comment by urishiraval** [comment]
@Calorion apologies, I will update the docs
