### ISSUE TITLE
Stuck on Loading Apple Reminders

### ISSUE THREAD

**Issue by maneeshsethi** [urishiraval/obsidian-apple-reminders-plugin#14]
Hiya. I managed to get Obsidian to request Apple Reminders access using the [Snippets](https://github.com/cristianvasquez/obsidian-snippets-plugin) extension. 

Unfortunately --- the plugin is still stuck on 'Loading Apple Reminders...'. It does not seem to move to the next step.
Any clue what's going wrong? I know that Obsidian can access the reminders (see screenshots below), but this plugin doesn't....

Note: I'm using the Community Plugins installer. Would there be a difference if I cloned the repo manually?

Thanks

For reference, Here's the code I used to request permissions:

![CleanShot 2022-09-15 at 10 32 23](https://user-images.githubusercontent.com/620799/190356190-37345802-14ec-4e85-8e50-79732f3e9a80.png)

![CleanShot 2022-09-15 at 10 31 40](https://user-images.githubusercontent.com/620799/190356145-131dc232-2ee4-4e03-a331-18e2af60809c.png)

**Comment by urishiraval** [comment]
Please use ```apple-reminders instead of ```reminders
