### ISSUE TITLE
All dates showing as "Invalid Date"

### ISSUE THREAD

**Issue by mjsalam** [urishiraval/obsidian-apple-reminders-plugin#2]
Hi,

Thanks for this plugin!  I am using the latest version of plugin with latest Obsidian - all tasks showing "Invalid Date" subsequently no date filtering is functioning as expected.

**Comment by urishiraval** [comment]
Hi...I've tested it now on my device and there doesn't seem to be an issue.

Could you provide more information on what laptop you're using?

The plugin uses AppleScript to fetch the data so the obsidian version shouldn't break anything usually.

**Comment by mjsalam** [comment]
Hey. Interesting. I’m using a Mac - Big Sur latest.

**Comment by urishiraval** [comment]
Thats weird.....could you then run the following script in the Script Editor?

```AppleScript
tell list 'list_name' in application "Reminders"
   set buffer to ((current date) - minutes * 5)
   return properties of reminders whose completion date comes after buffer or completed is false	
end tell
```

Where 'list_name' is the name of your list

(To open the editor just type 'Script' in spotlight and it should come up)

**Comment by urishiraval** [comment]
Also could you maybe attach a screen shot of what it looks like?

**Comment by mjsalam** [comment]
Had to change the single quote to double quotes as I was getting syntax error.  Output:
