### ISSUE TITLE
Fetching Reminders From Nextcloud Deck 

### ISSUE THREAD

**Issue by natarslan** [urishiraval/obsidian-apple-reminders-plugin#3]
**How I tried using the plugin?**
My Nextcloud CalDAV is connected to apple reminders. I use Nextcloud's Deck application to organise my tasks. The tasks in the Deck in return are connected to CalDAV and thus to Apple reminders. 

Nextcloud automatically names the list name to appear in Apple. So if my Deck is named "mybeautifuldeck" (in Nextcloud), it will appear as "Deck: mybeautifuldeck" in Apple reminder. 

**The issue**
To fetch reminders from a list we need to write "list: List Name" in a code block. But the deck name has a colon sign it self. So it becomes "list: Deck: mybeautifuldeck"

**Request**
It would be very nice to be able to enter colon (and perhaps other signs) in the list name. Maybe something like 
" list: 'Deck: mybeautifuldeck' "
This way Nextcloud Deck reminders can be seen inside Obsidian.

**Comment by urishiraval** [comment]
Hi @natarslan ,

The block uses yaml format. So that format you specified where `list: '<name with special characters'` does work.

Let me know if there are any issues.

**Comment by natarslan** [comment]
Ah, my bad! After restarting the obsidian it worked. I have somehow missed it. Oh this made my day!
