### ISSUE TITLE
Missing lists under groups

### ISSUE THREAD

**Issue by KristianOellegaard** [urishiraval/obsidian-apple-reminders-plugin#4]
Currently lists under groups are not available. However, it also appears you can't find them with apple script - however - I noticed you can actually get the to-do items from lists coming from groups.

This means it should be possible to query them by `id` and the user could get this ID by temporarily moving it outside the group and then querying the lists with apple script.

```
tell application "Reminders" to return properties of lists
```

and then the plugin should be able to accept not the name of the list but the ID as well, e.g.

```reminders
list_id: "00000-fffffffff-0000000-fffffffff-0000000"
```

**Comment by urishiraval** [comment]
It's a good idea...I'm actually working on being able to move reminders between lists right now

I'm wondering whether it would be a good idea to have a "Unassigned" list that would basically just pull in all reminders from groups
