### ISSUE TITLE
App never requests Reminders permission, never functions on Mojave.

### ISSUE THREAD

**Issue by maneeshsethi** [urishiraval/obsidian-apple-reminders-plugin#9]
Hello. I'm using this plugin on a Mac M1 Mojave.

The app shows as if it's working (the tool bar says "Apple Reminders Sync enabled") but the app doesn't do anything. 

I noticed, after copying an osascript from the source file and running it in terminal, that the terminal requested permissions to Reminders.App before it would function. However, I can't drag and drop Obsidian onto this column like other rows in Security & Privacy -- the app needs to request it (which it never does).

Here is a loom video demonstrating the issue: 

[Obsidian-apple-reminders plugin request for help - Watch Video](https://www.loom.com/share/65cc4f509f8a4c64bf6044b55a7939b9)

Can anyone help me get this to work?

**Comment by donzthefonz** [comment]
Also experiencing this issue on Monterey

**Comment by danielskowronski** [comment]
For bump and reference: same on Ventura. 

And in that macOS version, I can no longer find an option to manually grant permission for the app that never asked for it.

**Comment by urishiraval** [comment]
This is going to be a rough one to debug....I can smell it 😂

Thanks for the video @maneeshsethi

**Comment by urishiraval** [comment]
@maneeshsethi @danielskowronski  @donzthefonz  Please update and try again.

Please do let me know if there are more issues

**Comment by danielskowronski** [comment]
On macOS 13.0 now, reinstalled plugin version 2.0.0 and restarted entire Obsidian - still stuck on `Loading Apple Reminders...`.
Nothing in console except `Apple Reminders: styles.css not found`

**Comment by urishiraval** [comment]
@danielskowronski I'm trying to debug but it works perfectly on both my work MacBook and my personal one.

Have you tried opening the Reminders app while obsidian is loading?

Another thing I can think of is to open the 'Scripts' application and  run something generic like:

'''
tell application "Reminders"
end tell
'''

**Comment by maneeshsethi** [comment]
@urishiraval it's stuck on 'Loading Apple Reminders...'

What is the 'Scripts' application? Is this an obsidian plugin or what?

**Comment by danielskowronski** [comment]
I can confirm that Apple Script can talk to Reminders app (@maneeshsethi: it's built-in macOS app / language to talk to apps - `Script Editor.app` is GUI for that).

**Comment by urishiraval** [comment]
Hi @danielskowronski and @maneeshsethi , please attach the snipped you are using in the note to get your lists.

It's been brought to my attention (see [issue #11](https://github.com/urishiraval/obsidian-apple-reminders-plugin/issues/11#issuecomment-1254317755)) that there is a miss print in the documentation.

**Comment by timt1961** [comment]
Can confirm that with 'apple-reminders' instead of 'Reminders' I see a spinner; however,
```apple-reminders
list: All
```
reports "No reminders found"

**Comment by urishiraval** [comment]
@timt1961 This is interesting...moving this to another issue
